function p_cplx(note, val)
    
if imag(val) < 0
    fprintf("%s:  %0.2f  %0.2f   |%0.2f|angle(%0.2f or %0.2f)\n",...
       note,...
       real(val), ...
       imag(val), ...
       abs(val), ...
       rad2deg(angle(val)), ...
       angle(val));
else
    fprintf("%s:  %0.2f + %0.2f   |%0.2f|angle(%0.2f or %0.2f)\n",...
       note,...
       real(val), ...
       imag(val), ...
       abs(val), ...
       rad2deg(angle(val)), ...
       angle(val));
end

end